name: Nessie CI

on: [ pull_request, release ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: Install deno
        uses: denolib/setup-deno@master
        with: 
          deno-version: 1.0.0
      - name: Check formatting
        run: deno fmt --check
      - name: Run tests
        run: make test
